/* -----------------------------------------------------------------------------
 * title:  even_fib.c
 * author: Guy J. Bianco IV
 *
 * Project Euler
 *   Problem 2 <http://projecteuler.net/problem=2>
 *
 * From the page:
 *  "Each new term in the Fibonacci sequence is generated by adding the
 *   previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *   By considering the terms in the Fibonacci sequence whose values do not
 *   exceed four million, find the sum of the even-valued terms."
 *
 * History:
 *   Dec 12, 2013 - initial version
 *
 * -----------------------------------------------------------------------------
 */

#include <stdio.h>
#include <stdlib.h>

#ifndef DEBUG
#define DEBUG 0
#endif

#define MAX 4000000 /* four million */

int main() {
	int sum  = 0;
	int fib1 = 1;
	int fib2 = 2;

	while(1) {
		if(DEBUG)
			printf("fib: %d\n", fib1);

		if(fib1 > MAX)
			break;
		if(fib1 % 2 == 0) {
			if(DEBUG)
				printf("\tdiv by 2\n");
			sum += fib1;
		}
		fib1 += fib2;

		if(DEBUG)
			printf("fib: %d\n", fib2);

		if(fib2 > MAX)
			break;
		if(fib2 % 2 == 0) {
			if(DEBUG)
				printf("\tdiv by 2\n");
			sum += fib2;
		}
		fib2 += fib1;
	}

	printf("even sum: %d\n", sum);

	return 0;
}
