/* -----------------------------------------------------------------------------
 * title:  even_fib.c
 * author: Guy J. Bianco IV
 *
 * Project Euler
 *   Problem 2 <http://projecteuler.net/problem=2>
 *
 * From the page:
 *  "Each new term in the Fibonacci sequence is generated by adding the
 *   previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *   By considering the terms in the Fibonacci sequence whose values do not
 *   exceed four million, find the sum of the even-valued terms."
 *
 * History:
 *   Dec 12, 2013 - initial version (works)
 *   Dec 12, 2013 - optimize: remove mod
 *
 * -----------------------------------------------------------------------------
 */

#include <stdio.h>
#include <stdlib.h>

int main() {
	int fib1=1, fib2=2, sum=0, max=4000000;
	char m=1;

	while(fib1 <= max && fib2 <= max) {
		if( (fib1 & m) == 0)
			sum += fib1;
		fib1 += fib2;

		if( (fib2 & m) == 0)
			sum += fib2;
		fib2 += fib1;
	}
	printf("sum: %d\n", sum);

	return 0;
}
